/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dynamicNftSol from "./DynamicNft.sol";
export type { dynamicNftSol };
export type { CarlGalleryClub } from "./CarlGalleryClub";
